name: Github PRs CI

on:
  push:
    branches:
    - master
    paths: 
    - 'Intellias_Upskill_Practice_new/**'
  pull_request:
    types: opened
    paths: 
      - 'Intellias_Upskill_Practice_new/**'

jobs:
 build:
    runs-on: Ubuntu-latest
 
    steps:
      - uses: actions/checkout@v3
      - uses: cpp-linter/cpp-linter-action@v2
        id: linter
        env:
          continue-on-error: true
          files-changed-only: false
          VALIDATE_ALL_CODEBASE: true
          DEFAULT_BRANCH: master
          IGNORE_GENERATED_FILES: true 
          IGNORE_GITIGNORED_FILES: true
          VALIDATE_C++_clang-format: true
        with:
          style: file
          fetch-depth: 0
          
          
      - name: Fail fast?!
        if: steps.linter.outputs.checks-failed > 0
        run: echo "Some files failed the linting checks!"
      
      - name: Build with Windows C++
        run:  cpp build ./NewImageProcessingSDK.sln --configuration Debug
      
        
